$-w = false
$" = ["enumerator.so", "etc.bundle", "fileutils.rb"]
$$ = 367
$-F = nil
$* = ["/Users/davidpr/Desarrollos/Desarrollos js/.metadata/.plugins/com.aptana.ruby.core/-1085973036/4"]
$. = 1598
$KCODE = "NONE"
$fileutils_rb_have_lchown = nil
$-p = false
$stderr = IO.new
$, = nil
$` = nil
$@ = nil
$-v = false
$LOAD_PATH = ["/Library/Ruby/Site/1.8", "/Library/Ruby/Site/1.8/powerpc-darwin12.0", "/Library/Ruby/Site/1.8/universal-darwin12.0", "/Library/Ruby/Site", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8/universal-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/powerpc-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0", "."]
$< = ARGF
$; = nil
$PROGRAM_NAME = "/Applications/Aptana Studio 3/configuration/org.eclipse.osgi/bundles/444/1/.cp/ruby/core_stubber.rb"
$-i = nil
$deferr = IO.new
$\ = nil
$= = false
$-d = false
$stdout = IO.new
$& = nil
$-a = false
$VERBOSE = false
$-I = ["/Library/Ruby/Site/1.8", "/Library/Ruby/Site/1.8/powerpc-darwin12.0", "/Library/Ruby/Site/1.8/universal-darwin12.0", "/Library/Ruby/Site", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8/universal-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/powerpc-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0", "."]
$0 = "/Applications/Aptana Studio 3/configuration/org.eclipse.osgi/bundles/444/1/.cp/ruby/core_stubber.rb"
$FILENAME = "-"
$defout = IO.new
$-0 = "\n"
$+ = nil
$fileutils_rb_have_lchmod = nil
$DEBUG = false
$LOADED_FEATURES = ["enumerator.so", "etc.bundle", "fileutils.rb"]
$? = nil
$stdin = IO.new
$~ = nil
$: = ["/Library/Ruby/Site/1.8", "/Library/Ruby/Site/1.8/powerpc-darwin12.0", "/Library/Ruby/Site/1.8/universal-darwin12.0", "/Library/Ruby/Site", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby/1.8/universal-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/vendor_ruby", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/powerpc-darwin12.0", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin12.0", "."]
$_ = nil
$-K = "NONE"
$-l = false
$> = IO.new
$/ = "\n"
$' = nil
$SAFE = 0
$! = nil
